<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>bef147c9-0073-4436-9e8c-046aa4c479fa</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageReference Include="QuestPDF" Version="2026.9.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DaoLibrary\DaoLibrary.csproj" />
    <ProjectReference Include="..\ServiceLibrary\ServiceLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\database\migrations\*.sql">
      <LogicalName>ApiGestion.Database.Migrations.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
